name: Android CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: setup android-ndk
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r23
        add-to-path: true
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build saffal
      run: |
          git submodule update --init
          pushd saffal/src/main/jni
          ndk-build
          popd
          cd app
          ../gradlew assembleRelease
